name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      run_format:
        description: "Run optional clang-format check job"
        required: false
        type: boolean
        default: false

jobs:
  build-test:
    name: Build and Test (${{ matrix.os }} / exceptions=${{ matrix.exceptions }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        exceptions: [on, off]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure
        shell: bash
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build (exceptions on)
        run: cmake --build build --config Debug --parallel 2

      - name: Test (exceptions on)
        run: ctest --test-dir build --output-on-failure -C Debug

      - name: Build/Test (exceptions off)
        if: matrix.exceptions == 'off'
        run: |
          cmake --build build --target tc_tests_noex --config Debug --parallel 2
          ctest --test-dir build -C Debug -R tc_tests_noex --output-on-failure


      - name: Analyze (clang-tidy)
        if: matrix.os == 'ubuntu-latest' && matrix.exceptions == 'on'
        run: |
          sudo apt-get update && sudo apt-get install -y clang-tidy
          cmake -S . -B build-tidy -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cmake --build build-tidy --parallel 2
          run-clang-tidy -p build-tidy || true

  format-check:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_format == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install clang-format
        run: |
          sudo apt-get update && sudo apt-get install -y clang-format-18 || sudo apt-get install -y clang-format
          sudo ln -sf /usr/bin/clang-format-18 /usr/local/bin/clang-format || true
          clang-format --version
      - name: Run clang-format diff check
        run: |
          git ls-files '*.hpp' '*.h' '*.cpp' | xargs -r clang-format --style=file --dry-run --Werror
